on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#    - name: Install and configure Poetry
#      uses: snok/install-poetry@v1
#      with:
#        version: 1.2.2
#        virtualenvs-create: true
#        virtualenvs-in-project: true
#        installer-parallel: true
#        virtualenvs-path: .venv
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10.7"
    - uses: Gr1N/setup-poetry@v8
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        poetry-version: "1.2.2"
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      env:
        POETRY_VIRTUALENVS_IN_PROJECT=true
    - run: poetry install --no-dev && ls -la
#    - name: Debug -> ls -la
#      run: ls -la
#    - name: rsync app deployment
#      uses: burnett01/rsync-deployments@5.2.1
#      with:
#        switches: -avzr --exclude=".git" --exclude=".github"
#        path: /
#        remote_path: /var/www/wedding-fullstack/
#        remote_host: ${{ secrets.SSH_HOST }}
#        remote_port: ${{ secrets.SSH_PORT }}
#        remote_user: ${{ secrets.SSH_USER }}
#        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
#    - name: rsync apache config deployment
#      uses: burnett01/rsync-deployments@5.2.1
#      with:
#        switches: -avzr
#        path: /sites-available/wedding-fullstack.conf
#        remote_path: /etc/apache2/sites-available/wedding-fullstack.conf
#        remote_host: ${{ secrets.SSH_HOST }}
#        remote_port: ${{ secrets.SSH_PORT }}
#        remote_user: ${{ secrets.SSH_USER }}
#        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
#    - name: Restart Apache Server via SSH
#      uses: appleboy/ssh-action@v0.1.7
#      with:
#        host: ${{ secrets.SSH_HOST }}
#        username: ${{ secrets.SSH_USER }}
#        key: ${{ secrets.SSH_PRIVATE_KEY }}
#        port: ${{ secrets.SSH_PORT }}
#        script: systemctl restart apache2
