on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

name: Rsync Deployment
jobs:
  deployment:
    name: Rsync Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
        
      - name: Write SSH Key To File
        run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.VPS_PRIVATE_KEY}}
          
      - name: Debug -> List Files
        run: 'ls -la'
          
      - name: Rsync Deployments Action
        run: rsync -avz --dry-run -e "ssh -i key" / ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/basic-flask-apache-app/ 
