on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.7"
    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.2.2"
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Install Poetry Dependencies
      run: poetry install --no-dev
      env:
        POETRY_VIRTUALENVS_IN_PROJECT: true
    - name: Deploy App With Rsync
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --exclude=".git" --exclude=".github"
        path: /
        remote_path: /var/www/wedding-fullstack/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy Config File With Rsync
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr
        path: /sites-available/wedding-fullstack.conf
        remote_path: /etc/apache2/sites-available/wedding-fullstack.conf
        remote_host: ${{ secrets.SSH_HOST }}
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Restart Apache Server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: systemctl restart apache2
