on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

name: Rsync Deployment
jobs:
  deployment:
    name: Rsync Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
          
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Fix known_hosts IP
        run: sed -i 's/github.com/${{ secrets.VPS_HOST }}/g' /home/runner/.ssh/known_hosts

#       - name: Fix known_hosts IP
#         run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> /home/runner/.ssh/known_hosts
          
      - name: Debug -> List Files
        run: 'cat /home/runner/.ssh/known_hosts'
          
      - name: Rsync Deployments Action
        run: rsync -avz --dry-run -e "ssh -i /home/runner/.ssh/id_rsa" / ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/basic-flask-apache-app/ 
